apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsdeployment
  labels:
    app: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node.jsapp
  template:
    metadata:
      labels:
        app: node.jsapp
    spec:
      containers:
      - name: node.jsapp
        image: localhost/nodejs_mode:$BUILD_ID
        ports:
        - containerPort: 5000
