apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsdeployment
  labels:
    app: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
      - name: nodejsapp
        image: sharon111edapal/nodejs_modi:$BUILD_ID
        ports:
        - containerPort: 5000
