apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsdeployment
  labels:
    app: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
      - name: nodejsapp
        image: sharon111edapal/nodejs_modi:$BUILD_ID
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: nodeport
spec:
  type: NodePort
  selector:
    app: nodejsapp
  ports:
    - port: 5000
      protocol: TCP
        #targetPort: 80     # Application listening port in Pod    # PodIP:80
      nodePort: 30033

